#!/usr/bin/env bash
# configuring a server by bash script
apt-get -y update
apt-get -y install nginx
sudo sed  '/server_name _;/a return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4' /etc/nginx/sites-enabled/default
echo 'Holberton School' | tee /var/www/html/index.html
service nginx restart
