#!/usr/bin/env bash
# Install HAProxy and configure the load balancer with 2 web servers

apt-get -y update
apt-get -y install haproxy=1.6.\*
echo "backend web-backend
        balance roundrobin
        server 870-web-01 34.74.133.160:80 check
        server 870-web-02 34.74.43.84:80 check" >> /etc/haproxy/haproxy.cfg
echo "frontend http
        bind *:80\
        mode http
        default_backend web-backend" >> /etc/haproxy/haproxy.cfg
service haproxy restart
