#!/usr/bin/env bash
# 5-4_bad_luck_8_is_your_chance: 4 for bad luck 8 for good

i=1

while (( i <= 10 )); do
    if (( i == 4 )); then
        echo "bad luck"
    elif (( i == 8 )); then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    (( i++ ))
done